### ISSUE TITLE
Error: ambiguous command "/join"

### ISSUE THREAD

**Issue by Wizhi** [poljar/weechat-matrix#137]
This might be quite a noob question, but I can't seem to find anything about this issue anywhere.

Totally new to WeeChat, but it seems really cool.

After installing `weechat-matrix` as a plugin, from following the instructions in the readme, I can't seem to actually join any rooms.

```
Error: ambiguous command "/join": it exists in many plugins and not in "core" plugin
```

Is there some extra step I should be aware of?

I'm on Arch, using WeeChat 2.6, commit `c1b8fe97c35ecbca0a51d3a336b118a972688388`.

**Comment by poljar** [comment]
Since multiple plugins can implement commands you'll need to pick the right buffer from which you'll run your command.

Make sure to switch to a buffer that is owned by this script. If you're not in any rooms your Matrix server buffer will do.

If your server buffers are merged with the core buffer you can switch between them using `CTRL-X`.

**Comment by Wizhi** [comment]
Well that was fast.

Thanks for the explanation!

 I'll go read through the WeeChat documentation. :)
