### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by dvzrv** [poljar/weechat-matrix#166]
Hi! I would like to package weechat-matrix for Arch Linux.

It would be awesome, if a [setuptools](https://setuptools.readthedocs.io/en/latest/) or [poetry](https://python-poetry.org/) integration was created, so that the package can be installed system-wide (properly tracking dependencies).
The contrib scripts which are required in `PATH` can then either be installed during packaging (manually) or be defined by an `entry_point` ([setuptools](https://setuptools.readthedocs.io/en/latest/setuptools.html?highlight=entry_point#automatic-script-creation), [poetry](https://python-poetry.org/docs/pyproject/#scripts) examples).

Afterwards, all that is needed is:

* create symlink for user to globally installed `main.py` (on demand, maybe via helper script)
* tag a version of this repository

**Comment by poljar** [comment]
e80dee57e8e1cfdc5de948da6fd9a1c2f8909a8c adds a poetry file, this produces a tarball with the following contents:

```
matrix-0.1.0/LICENSE
matrix-0.1.0/contrib/matrix_decrypt.py
matrix-0.1.0/contrib/matrix_sso_helper.py
matrix-0.1.0/contrib/matrix_upload.py
matrix-0.1.0/main.py
matrix-0.1.0/matrix/__init__.py
matrix-0.1.0/matrix/_weechat.py
matrix-0.1.0/matrix/bar_items.py
matrix-0.1.0/matrix/buffer.py
matrix-0.1.0/matrix/colors.py
matrix-0.1.0/matrix/commands.py
matrix-0.1.0/matrix/completion.py
matrix-0.1.0/matrix/config.py
matrix-0.1.0/matrix/globals.py
matrix-0.1.0/matrix/message_renderer.py
matrix-0.1.0/matrix/server.py
matrix-0.1.0/matrix/uploads.py
matrix-0.1.0/matrix/utf.py
matrix-0.1.0/matrix/utils.py
matrix-0.1.0/pyproject.toml
matrix-0.1.0/setup.py
matrix-0.1.0/PKG-INFO
```

The contrib scripts and `main.py` will need to be manually moved to sensible folder.

Any objections or can i tag this?

**Comment by poljar** [comment]
I pushed a tag now. If something is missing please shout.

**Comment by eli-schwartz** [comment]
```
$ dephell deps convert --from pyproject.toml --to setup.py
WARNING cannot find tool.dephell section in the config (path=pyproject.toml)
ERROR InvalidSpecifier: ^3.7.4; 
```

The pyproject.toml is invalid, the following will fix it:

```diff
-typing = "^3.7.4; python_version < 3.5"
+typing = { python = "< 3.5", version = "^3.7.4" }
```

Note that `poetry build -f sdist` has incorrect behavior, rather than erroring on this, it simply generates a dependency on

```
typing = "*"
```

which is *not* what you want.

Also you're installing three modules available to the interpreter as:

```
import matrix
import contrib
import main
```

and I'm not sure why, since the second and third are completely inappropriate in context. They'll clash with the global namespace, and it's very unlikely you want them installed at all.

Since poetry doesn't support the setuptools `scripts` keyword for directly installing a script file to the bin/ directory, it only supports console_scripts entry points, you'd need to install the contrib directory as a `matrix.config` module and generate wrapper scripts if you wanted this to work out of the box. Personally, I'd recommend using setuptools directly, you can do it in a very declarative fashion with [setup.cfg](https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files)

Alternatively, change this:

https://github.com/poljar/weechat-matrix/blob/2a24096505a7967919b7a69b8bb75db836ac0f75/pyproject.toml#L7-L11

to include `, format = "sdist"` for packages which you only want to include in sdist tarballs but which should NOT be installed. Users would have to manually copy over these scripts for packaging.

(Where are these sdists uploaded? It conflicts with https://pypi.org/project/matrix/)

**Comment by eli-schwartz** [comment]
Actually I don't even understand the typing dependency at all, since python 3.5 is not permitted due to specifying 

```
[tool.poetry.dependencies]
python = "^3.8"
```

**Comment by eli-schwartz** [comment]
#170 fixes the invalid syntax only.

**Comment by poljar** [comment]
> and I'm not sure why, since the second and third are completely inappropriate in context. They'll clash with the global namespace, and it's very unlikely you want them installed at all.

Sorry, I may have misunderstood what was wanted here so I wasn't paying much attention to the poetry setup. I assumed that only a tarball is needed and that this won't be treated as a normal python package, which it really isn't.

> (Where are these sdists uploaded? It conflicts with https://pypi.org/project/matrix/)

They are not on pypi and I have no intentions to put them on pypi, this is not a normal python package it does not work unless it's run from inside of Weechat.

**Comment by eli-schwartz** [comment]
> I assumed that only a tarball is needed and that this won't be treated as a normal python package, which it really isn't.

If you `git tag` the repo then github creates a tarball.



> this is not a normal python package it does not work unless it's run from inside of Weechat.

The idea was that the library can be installed to site-packages and I guess the scripts could be run with `/exec` or whatever. One possibility for main.py would be to install it to /usr/share/weechat-scripts/ so people can symlink that.

If one isn't using poetry to install, there is little point in downloading the Github Releases tarball, then running `poetry build -f sdist` to make a second tarball based on the first tarball, then throwing out the setup.py and cp'ing files around by hand.

**Comment by poljar** [comment]
I pushed a new tag, hopefully I didn't miss anything else you mentioned.
