### ISSUE TITLE
Nicks in nick list do not resemble nicks in message buf

### ISSUE THREAD

**Issue by craftyguy** [poljar/weechat-matrix#19]
Not sure if this is intended, but the nicks of folks in matrix channels are in the format @<nick>:<server>. This conflicts with the way that IRC uses @ to designate OP (not that it has much meaning on matrix), but also the way nicks are displayed in the message portion of the buffer is different than how they show in the nick list, so mentioning a nick is awkward/difficult since you have to know how it shows in the nick list in order for tab completion to work.

I can take a shot at fixing this if this is something you think should be improved (e.g. nicks in message portion of buffer == nicks in nick list).

**Comment by craftyguy** [comment]
Nice, thanks. After stumbling for a bit to get your nio and python-olm packages built/installed on Arch, I am now successfully running your olm-command branch and the nicks appear sane now :)

**Comment by craftyguy** [comment]
This isn't really related to the original thing I reported, but since I don't think it warrants a new 'issue' (and I know of no other way to get ahold of you to ask): 

What is your workflow developing this script for weechat? Can you run a debugger (e.g. pdb)? (being able to do that would help me to pick apart the code and figure out what changes I might need to make for, e.g., the display name thing)

**Comment by poljar** [comment]
Sadly pdb can't be run inside of weechat (or at least I don't know how). Changes to nio ideally include logging and tests, those can be done non-interactively and offline quite easily.

For weechat it's a little bit harder, I included settings to enable debugging, those messages can be helpful. If I'm doing some protocol changes i set up a proxy for the connection and use mitmproxy to check the traffic. Proxies work for the matrix script in the same way as for the irc plugin.

Utilizing display names has two problems for now:
- Display names can change and nick changes aren't implemented yet
- Display can be maliciously set up, to e.g. collide, be annoyingly long 

The first one is relatively easy to solve the second one needs to be figured out how to deal with them. Note collisions are already somewhat handled since i don't use the full mxid for nicks. If a collision happens the second nick gets a full mxid.

Anyways the code that handles user adding is [here](https://github.com/poljar/weechat-matrix/blob/olm-command/matrix/buffer.py#L957).

If you have further questions feel free to ask here or via mail. There is also a room set up for development: [#weechat-matrix:termina.org.uk](https://matrix.to/#/!CXdtRNzcKrepbjaPlq:termina.org.uk?via=termina.org.uk)
