### ISSUE TITLE
python-future issue? I have it installed.

### ISSUE THREAD

**Issue by mmsenxxx** [poljar/weechat-matrix#97]
Just installed, followed instructions. End result:

03:29:41 weechat | python: loading script "/home/xxxxxx/.weechat/python/matrix.py"
03:29:41 weechat | python: stdout/stderr (?): Traceback (most recent call last):
03:29:41 weechat | python: stdout/stderr (?): File "/home/xxxxxx/.weechat/python/matrix.py", line 25, in 
03:29:41 weechat | python: stdout/stderr (?): from builtins import str
03:29:41 weechat | python: stdout/stderr (?): ImportError: No module named builtins
03:29:41 weechat =!= | python: unable to parse file "/home/xxxxxx/.weechat/python/matrix.py""

**Comment by poljar** [comment]
Can you give a little bit more info? 

- What python version is Weechat compiled with. 
- Are you sure that you installed the future module for the correct python version?
- Does importing the builtins module work from a python interpreter?
- Did you try restarting Weechat? It may not pick up new libraries without a restart.

**Comment by mmsenxxx** [comment]
Ok. Thanks for your patience. I've resolved the issue.

**Comment by poljar** [comment]
Could you write up what the problem was? Maybe someone hits the same issue and finds this thread useful.

**Comment by jazzyeagle** [comment]
I would have found this thread helpful.  I just had this same issue now.

The issue for me (on Parabola, a derivative of ArchLinux) is that the packages are found when building, because my system is set up to use Python 3, and so building weechat-matrix uses the python 3 directory and finding them all.  When it goes to run in Weechat (which is built for Python 2), it looks in the python 2 directory and doesn't find any of the packages.

Installing all of the python2 versions of the required packages fixed the problem for me.

**Comment by lf94** [comment]
FWIW I also ran into this problem today.
